import type { Guide, GuideSections } from "./types";
import { SECTION_ORDER, SECTION_LABELS } from "./types";

/**
 * Serialise a complete Guide into a portable Markdown document.
 *
 * Used by the Export button (client-side download) — keep it dependency-free so
 * it runs in the browser. Sections are emitted in canonical SECTION_ORDER.
 */
export function guideToMarkdown(guide: Guide): string {
  const { sections } = guide;
  const out: string[] = [];

  // ── Title + metadata ─────────────────────────────────────────────────────
  out.push(`# Onboarding Guide — ${guide.repoName}`);
  out.push("");
  out.push(`> Generated by [Meridian](https://github.com/RahulSriv/meridian) — your reference line for any codebase.`);
  out.push("");

  const meta: string[] = [];
  if (guide.repoUrl) meta.push(`**Repository:** ${guide.repoUrl}`);
  if (guide.generatedAt) {
    meta.push(`**Generated:** ${new Date(guide.generatedAt).toUTCString()}`);
  }
  if (guide.commitSha) meta.push(`**Commit:** \`${guide.commitSha.slice(0, 7)}\``);
  if (meta.length) {
    out.push(meta.join("  \n"));
    out.push("");
  }

  out.push("---");
  out.push("");

  for (const key of SECTION_ORDER) {
    if (!sections?.[key]) continue;
    out.push(`## ${SECTION_LABELS[key]}`);
    out.push("");
    out.push(renderSection(key, sections));
    out.push("");
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function renderSection<K extends keyof GuideSections>(key: K, sections: GuideSections): string {
  switch (key) {
    case "overview": {
      const s = sections.overview;
      const parts = [s.summary?.trim() ?? ""];
      if (s.whatItIsNot?.trim()) {
        parts.push("", `**What it is _not_:** ${s.whatItIsNot.trim()}`);
      }
      return parts.join("\n");
    }

    case "architecture": {
      const s = sections.architecture;
      const parts = [s.narrative?.trim() ?? ""];
      if (s.keyPatterns?.length) {
        parts.push("", "**Key patterns:**", "");
        parts.push(...s.keyPatterns.map((p) => `- ${p}`));
      }
      return parts.join("\n");
    }

    case "readingOrder": {
      return sections.readingOrder
        .map((item, i) => {
          const head = `${i + 1}. \`${item.file}\`${item.timeEstimate ? ` _(${item.timeEstimate})_` : ""}`;
          return item.reason ? `${head}\n   ${item.reason}` : head;
        })
        .join("\n");
    }

    case "localSetup": {
      return sections.localSetup
        .map((step, i) => {
          const parts = [`${i + 1}. ${step.step}`];
          if (step.command) parts.push("", "   ```bash", `   ${step.command}`, "   ```");
          if (step.note) parts.push(`   > ${step.note}`);
          return parts.join("\n");
        })
        .join("\n\n");
    }

    case "gotchas": {
      return sections.gotchas
        .map((g) => {
          const tag = `\`${g.severity}\` · _${g.source}_`;
          return `### ${g.title}\n${tag}\n\n${g.description}`;
        })
        .join("\n\n");
    }

    case "techStack": {
      return sections.techStack
        .map((t) => {
          const name = t.version ? `**${t.name}** \`${t.version}\`` : `**${t.name}**`;
          return `- ${name} — ${t.whyUsedHere}`;
        })
        .join("\n");
    }

    case "ownership": {
      return sections.ownership
        .map((o) => {
          const files = o.files?.length ? o.files.map((f) => `\`${f}\``).join(", ") : "";
          const parts = [`### ${o.area}`];
          if (o.primaryOwner) parts.push(`**Primary owner:** ${o.primaryOwner}`);
          if (files) parts.push(`**Files:** ${files}`);
          return parts.join("\n");
        })
        .join("\n\n");
    }

    case "firstPRs": {
      return sections.firstPRs
        .map((pr) => `### ${pr.title}\n\`${pr.difficulty}\` · ${pr.area}\n\n${pr.description}`)
        .join("\n\n");
    }

    case "weekOnePlan": {
      const s = sections.weekOnePlan;
      const parts: string[] = [];
      if (s.day1?.length) {
        parts.push("**Day 1**", "");
        parts.push(...s.day1.map((d) => `- [ ] ${d}`));
      }
      if (s.week1?.length) {
        if (parts.length) parts.push("");
        parts.push("**Week 1**", "");
        parts.push(...s.week1.map((d) => `- [ ] ${d}`));
      }
      return parts.join("\n");
    }

    default:
      return "";
  }
}

/** Suggested filename for the downloaded guide, e.g. "owner-repo-onboarding.md". */
export function guideFilename(guide: Pick<Guide, "repoName">): string {
  const slug = guide.repoName.replace(/[^\w.-]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
  return `${slug || "meridian"}-onboarding.md`;
}
